from main_dashboard.models import *


# Adding university information to Database.

Universities(uni_name='Australian Catholic University', location='North Sydney', ratings=5).save()
Universities(uni_name='Macquarie University',location='North Ryde',ratings=5).save()
Universities(uni_name='University of New South Wales', location='Kensington', ratings=5).save()
Universities(uni_name='University of Technology Sydney', location='City', ratings=5).save()
Universities(uni_name='Western Sydney University',location='Parramatta',ratings=5).save()
Universities(uni_name='Torrens University Australia',location='Ultimo',ratings=5).save()
Universities(uni_name='University of New England',location='Parramatta',ratings=5).save()
Universities(uni_name='Charles Darwin University',location='Northern Territory',ratings=5).save()
Universities(uni_name='University of Melbourne',location='Melbourne',ratings=5).save()
Universities(uni_name='Australian National University',location='Canberra',ratings=5).save()
Universities(uni_name='Monash University',location='Melbourne',ratings=5).save()
Universities(uni_name='University of Adelaide',location='Adelaide',ratings=5).save()
Universities(uni_name='James Cook University',location='Townsville City',ratings=5).save()
Universities(uni_name='Queensland University of Technology',location='Brisbane',ratings=5).save()
Universities(uni_name='University of Wollongong',location='Wollongong',ratings=5).save()
Universities(uni_name='Flinders University',location='Adelaide',ratings=5).save()
Universities(uni_name='Griffith University',location='Brisbane, Gold Coast, Logan',ratings=5).save()
Universities(uni_name='Curtin University',location='Perth',ratings=5).save()
Universities(uni_name='La Trobe University',location='Melbourne',ratings=5).save()
Universities(uni_name='University of Newcastle',location='Callaghan',ratings=5).save()
Universities(uni_name='Victoria University',location='Melbourne',ratings=5).save()
Universities(uni_name='Deakin University',location='Geelong',ratings=5).save()
Universities(uni_name='University of Tasmania',location='Hobart',ratings=5).save()
Universities(uni_name='Murdoch University',location='Murdoch',ratings=5).save()
Universities(uni_name='RMIT University',location='Melbourne',ratings=5).save()
Universities(uni_name='Swinburne University of Technology',location='Hawthorn',ratings=5).save()
Universities(uni_name='Bond University',location='Gold Coast',ratings=5).save()
Universities(uni_name='Central Queensland University',location='Rockhampton',ratings=5).save()
Universities(uni_name='Charles Darwin University',location='Casuarina',ratings=5).save()
Universities(uni_name='Edith Cowan University',location='Joondalup',ratings=5).save()
Universities(uni_name='Southern Cross University',location='Lismore',ratings=5).save()
Universities(uni_name='University of the Sunshine Coast',location='Sunshine Coast',ratings=5).save()


# Adding UOS to USYD
uni_obj = Universities.objects.get(uni_name='The University Of Sydney')
Unitofstudy(uni=uni_obj, unit_name='ELEC2004    Electrical Engineering: Foundations', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC2302	Signals and Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC3104	Engineering Electromagnetics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC3608	Computer Architecture', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC3609	Internet Software Platforms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC3702	Management for Engineers', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC3803	Bioelectronics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC4505	Digital Communication Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC5203	Topics in Power Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC5508	Wireless Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ELEC5515	Gigabit Wireless Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO1103	Introduction to Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO1113	Object-Oriented Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO2150	Introduction to Health Data Science', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO2315	Introduction to IT Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO2222	Computing 2 Usability and Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO3333	Computing 3 Management', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO3406	Introduction to Data Analytics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INFO3315	Human-Computer Interaction', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3027	Algorithm Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3109	Programming Languages and Paradigms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3308	Introduction to Artificial Intelligence', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3419	Graphics and Multimedia', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3221	Distributed Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3530	Discrete Optimization', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3615	Computer Science Project', ratings=5).save()


# Adding UOS to UNSW
uni_obj = Universities.objects.get(uni_name='University of New South Wales')
Unitofstudy(uni=uni_obj, unit_name='COMP1511	Introduction to Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGG1000	Engineering Design and Innovation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1131	Maths 1A', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1141	Higher Maths 1A', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP1531	Software Engineering Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2521	Data Structures and Algorithms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1241	Higher Maths 1B', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2111	Systems Modelling & Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='SENG2021	Software Engineering Workshop 2B', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2041	Software Construction', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2511	Object-Orinated Design & Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3311	Database Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3331	Computer Networks & Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3141	Software System Design & Implementation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP4920	Management & Ethics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ECON1203	Business and Economic Statistics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3141	Software System Design & Implementation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3331	Computer Networks & Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ECON1101	Microeconomics1', ratings=5).save()


# Adding UOS to Macquarie University
uni_obj = Universities.objects.get(uni_name='Macquarie University')
Unitofstudy(uni=uni_obj, unit_name='COMP115     Introduction to Computer Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP125	    Fundamentals of Computer Science', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='DMTH137	    Discrete Mathematics I', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGG100	    Introduction to Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ISYS114	    Introduction to Database Design and Management', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP332	    Programming Languages', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP333	    Algorithm Theory and Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP335	    Distributed Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGG300	    Engineering Project Practices', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP229	    Object-Oriented Programming Practices', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP247	    Data Communications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP225	    Algorithms and Data Structures', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='DMTH237	    Discrete Mathematics II', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP420	    Software Engineering Research Thesis B', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP410	    Software Engineering Research Thesis A', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP430	    Software Engineering Practices', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP434	    Advanced Software Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGG400	    Industry Experience', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGG450	    Systems Design and Engineering', ratings=5).save()


# Adding UOS to University of Technology Sydney
uni_obj = Universities.objects.get(uni_name='University of Technology Sydney')
Unitofstudy(uni=uni_obj, unit_name='33130   Mathematical Modelling 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='48230   Engineering Communication', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='48023   Programming Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='31269   Business Requirements Modelling', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='33230   Mathematical Modelling 2', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='48024   Applications Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='31282   Systems Testing and Quality Management', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='31271   Database Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41035   Engineering Practice Preparation 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='31251   Data Structures and Algorithms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='31257   Information System Development Methodologies', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41093   Software Engineering Studio 1A', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41094   Software Engineering Studio 1B', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='48240   Design and Innovation Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41029   Engineering Research Preparation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='48270   Entrepreneurship and Commercialisation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41097   Software Engineering Studio 3A', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41055   Engineering Workplace Reflection', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41098   Software Engineering Studio 3B', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='41030   Engineering Capstone', ratings=5).save()


# Adding UOS to Western Sydney University
uni_obj = Universities.objects.get(uni_name='Western Sydney University')
Unitofstudy(uni=uni_obj, unit_name='300700.6	Statistical Decision Making', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300580.3	Programming Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='100483.2	Principles of Professional Communication 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='200025.2	Discrete Mathematics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300104.4	Database Design and Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300147.4	Object Oriented Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300096.6	Computer Organisation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300952.2	Wireless and Mobile Networks', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300103.4	Data Structures and Algorithms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300582.5	Technologies for Web Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300960.4	Mobile Applications Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300128.5	Information Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300115.3	Distributed Systems and Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300578.3	Professional Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300167.4	Systems Programming 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300579.6	Professional Experience', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300404.2	Formal Software Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300580.3	Programming Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300104.4	Database Design and Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300565.2	Computer Networking', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300582.5	Technologies for Web Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='300096.6	Computer Organisation', ratings=5).save()


# Adding UOS to Torrens University Australia
uni_obj = Universities.objects.get(uni_name='Torrens University Australia')
Unitofstudy(uni=uni_obj, unit_name='ALGORITHMS AND DATA STRUCTURES', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INTRODUCTION TO SOFTWARE ENGINEERING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATHS 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATHS 2', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATHS 3', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='2D GAME PROGRAMMING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='GAME DESIGN PRINCIPLE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INTRODUCTION TO COMPUTER GRAPHICS', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMPUTER ARCHITECTURE AND OPERATING SYSTEMS', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='NETWORKING AND DATABASE SYSTEMS', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='RAPID GAME PROTOTYPE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='GAME DEVELOPMENT PLAYSTATION', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='3D GRAPHICS PROGRAMMING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ARTIFICIAL INTELLIGENCE AND PHYSICS FOR GAMES', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='WORK INTEGRATED LEARNING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='SOCIAL ENTERPRISE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='PRODUCTION CAPSTONE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='PRE-PRODUCTION CAPSTONE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INTRODUCTION TO CLOUD COMPUTING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='INTRODUCTION TO SOFTWARE ENGINEERING', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CREATIVE ENTERPRISE', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='PROJECT BASED LEARNING STUDIO: TECHNOLOGY', ratings=5).save()


# Adding UOS to University of New England
uni_obj = Universities.objects.get(uni_name='University of New England')
Unitofstudy(uni=uni_obj, unit_name='COSC250	    Programming Paradigms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC330	    Parallel and Distributed Computing', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC350	    Artificial Intelligence', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC380	    Algorithms in Machine Learning', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='STAT210	    Statistical Modelling and Experimental Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='STAT330	    Statistical Learning', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='GENE210	    Introductory Genetics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='GENE251     Introduction to Breeding and Genetics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='GENE322	    Genetics of Populations', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM110	    Chemistry I', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM120	    Chemistry II', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM210	    Quantum and Thermal Structure', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM220	    Chemical Reactivity', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM250	    Analytical Chemistry', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM302	    Organic Structure and Reactivity', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='CHEM305	    Applied Physical Chemistry', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='WRIT101	    The Craft of Academic Writing', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC260	    Web Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC301	    Special Topic in Computing', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC340	    Computer Networks and Information Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COSC372	    Management Information Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='EM336	    Remote Sensing and Image Analysis', ratings=5).save()


# Adding UOS to University of Melbourne
uni_obj = Universities.objects.get(uni_name='University of Melbourne')
Unitofstudy(uni=uni_obj, unit_name='Engineering Systems Design 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Calculus 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Engineering Systems Design 2', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Calculus 2', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Engineering Computation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Linear Algebra', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Algorithms and Data Structures', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Object Oriented Software Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Software Modelling and Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Computer Systems', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='', ratings=5).save()


# Adding UOS to Charles Darwin University
uni_obj = Universities.objects.get(uni_name='Charles Darwin University')
Unitofstudy(uni=uni_obj, unit_name='Cultural Intelligence and Capability', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Design and Innovation: Communicating Technology', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Software Now', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Computing Fundamentals', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Operating Systems and Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Network Engineering Concepts', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Statistics', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Database Concepts', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Organisational Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Algorithm and Complexity', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Mobile Web Structures', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Digital Systems and Computer Architecture', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Building Interactive Software', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='The Mobile Paradigm', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Network Infrastructures', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Network Engineering Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Project Management', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Database-driven Web Applications', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='C Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Distributed Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Human Computer Interaction Design', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='Discrete Structures', ratings=5).save()


# Adding UOS to Charles Darwin University
uni_obj = Universities.objects.get(uni_name='Charles Darwin University')
Unitofstudy(uni=uni_obj, unit_name='COMP1600    Foundations of Computing', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2100    Software Design Methodologies', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2300    Computer Organisation and Program Execution', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2310    Systems, Networks and Concurrency', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2120    Software Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP2420    Introduction to Data Management, Analysis and Security', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3120    Managing Software Development', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3500    Software Engineering Project', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3530    Systems Engineering for Software Engineers', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP3600    Algorithms', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP4130    Managing Software Quality and Process', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP4450    Advanced Computing Research Methods', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP4800    Industrial Experience', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGN1211    Discovering Engineering', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='ENGN3230    Engineering Innovation', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1005    Discrete Mathematical Models', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP1100    Programming as Problem Solving', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP1130    Programming as Problem Solving (Advanced)', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP1110    Structured Programming', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='COMP1140    Structured Programming (Advanced)', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1013    Mathematics and Applications 1', ratings=5).save()
Unitofstudy(uni=uni_obj, unit_name='MATH1014    Mathematics and Applications 2', ratings=5).save()



